//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ExscudoTestnetGUI.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ExscudoTestnetGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;threads&quot;: 2,
        ///	&quot;coin&quot;: &quot;eon&quot;,
        ///	&quot;name&quot;: &quot;main&quot;,
        ///
        ///	&quot;upstreamCheckInterval&quot;: &quot;5s&quot;,
        ///
        ///	&quot;payouts&quot;: {
        ///		&quot;enabled&quot;: true,
        ///		&quot;interval&quot;: &quot;120m&quot;,
        ///
        ///		&quot;peer&quot;: &quot;peer.testnet.eontechnology.org:9443&quot;,
        ///		&quot;seed&quot;: &quot;&lt;SEED&gt;&quot;,
        ///
        ///		&quot;deadline&quot;: 60,
        ///		&quot;fee&quot;: 10,
        ///
        ///		&quot;raw&quot;: false,
        ///
        ///		&quot;timeout&quot;: &quot;10s&quot;,
        ///		&quot;threshold&quot;: 500000000
        ///	}
        ///
        ///}
        ///.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eon32 {
            get {
                object obj = ResourceManager.GetObject("eon32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] eon64 {
            get {
                object obj = ResourceManager.GetObject("eon64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Configuration file
        ///
        ///To connect to a peer, you need to set an address
        ///
        ///    &quot;peer&quot;: &quot;peer.testnet.eontechnology.org:9443&quot;,
        ///
        ///Seed for the account on behalf of which we will sign transactions
        ///
        ///    &quot;seed&quot;: &quot;...&quot;,
        ///
        ///Transaction’s secondary fields, are needed to manage the commission and the transaction lifetime
        ///
        ///    &quot;deadline&quot;: 60,
        ///    &quot;fee&quot;: 10,
        ///
        ///# Command description
        ///
        ///List of commands available
        ///
        ///Command     | Description
        ///:-----------|:--------
        ///refill      | Transfer coins from amount to de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMe {
            get {
                return ResourceManager.GetString("ReadMe", resourceCulture);
            }
        }
    }
}
