// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ExscudoTestnetGUI
{

    internal partial class commitClass
    {
        internal class Attachment2
        {

            [JsonProperty("amount")]
            public ulong Amount { get; set; }

            [JsonProperty("recipient")]
            public string Recipient { get; set; }


        }
    }

    internal partial class commitClass
    {
        internal class All2
        {

            [JsonProperty("type")]
            public int Type { get; set; }

            [JsonProperty("timestamp")]
            public ulong Timestamp { get; set; }

            [JsonProperty("deadline")]
            public uint Deadline { get; set; }

            [JsonProperty("fee")]
            public ulong Fee { get; set; }

            [JsonProperty("sender")]
            public string Sender { get; set; }

            [JsonProperty("signature")]
            public string Signature { get; set; }

            [JsonProperty("attachment")]
            public Attachment2 Attachment { get; set; }
        }
    }

    internal partial class commitClass
    {

        [JsonProperty("all")]
        public All2[] All { get; set; }
    }

}
