// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ExscudoTestnetGUI
{

    internal partial class responseClass
    {
        internal class State2
        {

            [JsonProperty("code")]
            public int Code { get; set; }

            [JsonProperty("name")]
            public string Name { get; set; }
        }
    }

    internal partial class responseClass
    {

        [JsonProperty("state")]
        public State2 State { get; set; }

        [JsonProperty("amount")]
        public ulong Amount { get; set; }

        [JsonProperty("deposit")]
        public ulong Deposit { get; set; }
    }

}
